### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by massimilianobraglia** [bnf/phpstan-psr-container#3]
Hello @bnf,
thank you for this one! Is this package released under a certain license?
I would like to understand if I can use it 😄

**Comment by bnf** [comment]
Thanks, fixed.

The License (GPL-2+) was (only) listed in composer.json, but I've now [added](https://github.com/bnf/phpstan-psr-container/commit/a5dc7f29491062d345d5abfe2bff678355a75175) the LICENSE.txt for Github to pick it up in the UI.
I also updated the composer.json declaration to the newer identifier: https://github.com/bnf/phpstan-psr-container/commit/358003ee95ef6606a349aea60e0ffda8334169d6

Released as 1.0.1

**Comment by massimilianobraglia** [comment]
Thanks a lot!
